import type { Issue } from "./types";
import { assetPath } from "./assets";

const roadTimeline = [
  { status: "reported" as const, labelEn: "Reported", labelHi: "रिपोर्ट किया", date: "18 Aug · 08:42", noteEn: "Photo and location verified", noteHi: "फोटो और जगह सत्यापित" },
  { status: "acknowledged" as const, labelEn: "Acknowledged", labelHi: "स्वीकार किया", date: "18 Aug · 10:16", noteEn: "Sent to Roads, PWD", noteHi: "सड़क विभाग को भेजा" },
  { status: "in_progress" as const, labelEn: "In progress", labelHi: "काम जारी", date: "20 Aug · 09:30", noteEn: "Repair crew assigned", noteHi: "मरम्मत दल नियुक्त" },
];

const rawSeedIssues: Issue[] = [
  {
    id: "PK-14028", category: "Roads", titleEn: "Deep pothole at Ambedkar Nagar turn", titleHi: "अंबेडकर नगर मोड़ पर गहरा गड्ढा", descriptionEn: "Large road cavity near the bus turn; risky for two-wheelers after rain.", descriptionHi: "बस मोड़ के पास बड़ा गड्ढा; बारिश के बाद दोपहिया वाहनों के लिए खतरनाक।", address: "Ambedkar Nagar Road", lat: 28.7041, lng: 77.1025, image: "/images/pothole.svg", supporters: 31, aliases: ["Riya M.", "A neighbour", "Kabir S."], status: "in_progress", severity: "high", reportedAgoEn: "10 days ago", reportedAgoHi: "10 दिन पहले", departmentEn: "Roads · Public Works Department", departmentHi: "सड़क · लोक निर्माण विभाग", roleEn: "Junior Engineer, Ward 14", roleHi: "कनिष्ठ अभियंता, वार्ड 14", escalationEn: "Assistant Engineer · grievance@ward14.demo", escalationHi: "सहायक अभियंता · grievance@ward14.demo", expectedEn: "3 Sep · 4 days remaining", expectedHi: "3 सितम्बर · 4 दिन बाकी", overdueDays: 0, mine: true, timeline: roadTimeline,
  },
  {
    id: "PK-14019", category: "Waste", titleEn: "Garbage piling beside Sabzi Mandi", titleHi: "सब्ज़ी मंडी के पास कचरे का ढेर", descriptionEn: "Mixed waste has blocked part of the footpath.", descriptionHi: "मिश्रित कचरे ने फुटपाथ का हिस्सा रोक दिया है।", address: "Sabzi Mandi Corner", lat: 28.7058, lng: 77.0998, image: "/images/waste.svg", supporters: 9, aliases: ["A neighbour", "Meera"], status: "contested", severity: "medium", reportedAgoEn: "6 days ago", reportedAgoHi: "6 दिन पहले", departmentEn: "Sanitation · Municipal Council", departmentHi: "स्वच्छता · नगर परिषद", roleEn: "Sanitary Inspector, Ward 14", roleHi: "स्वच्छता निरीक्षक, वार्ड 14", escalationEn: "Zonal Sanitation Officer · 1800-14-0014", escalationHi: "क्षेत्रीय स्वच्छता अधिकारी · 1800-14-0014", expectedEn: "Overdue by 2 days", expectedHi: "2 दिन की देरी", overdueDays: 2, timeline: [...roadTimeline.slice(0, 2), { status: "awaiting_confirmation", labelEn: "Marked resolved", labelHi: "ठीक बताया गया", date: "23 Aug · 16:20" }, { status: "contested", labelEn: "Contested by resident", labelHi: "निवासी ने चुनौती दी", date: "24 Aug · 08:12", noteEn: "New photo shows waste remains", noteHi: "नई फोटो में कचरा मौजूद" }],
  },
  {
    id: "PK-14033", category: "Drainage", titleEn: "Open drain near Kabir Basti lane 3", titleHi: "कबीर बस्ती गली 3 के पास खुली नाली", descriptionEn: "Drain cover is missing near the school route.", descriptionHi: "स्कूल जाने वाले रास्ते पर नाली का ढक्कन गायब है।", address: "Kabir Basti · Lane 3", lat: 28.7019, lng: 77.1044, image: "/images/drain.svg", supporters: 4, aliases: ["A neighbour"], status: "acknowledged", severity: "high", reportedAgoEn: "2 days ago", reportedAgoHi: "2 दिन पहले", departmentEn: "Drainage · Municipal Engineering", departmentHi: "जल निकासी · नगर अभियांत्रिकी", roleEn: "Works Supervisor, Ward 14", roleHi: "कार्य पर्यवेक्षक, वार्ड 14", escalationEn: "Ward Engineer · 1800-14-0014", escalationHi: "वार्ड अभियंता · 1800-14-0014", expectedEn: "30 Aug · tomorrow", expectedHi: "30 अगस्त · कल", timeline: roadTimeline.slice(0, 2),
  },
  {
    id: "PK-14011", category: "Lighting", titleEn: "Streetlight out by community park", titleHi: "सामुदायिक पार्क की स्ट्रीट लाइट बंद", descriptionEn: "The corner stays dark after sunset.", descriptionHi: "सूर्यास्त के बाद मोड़ पर अंधेरा रहता है।", address: "Model Town Community Park", lat: 28.707, lng: 77.105, image: "/images/light.svg", supporters: 12, aliases: ["Dev", "A neighbour"], status: "confirmed", severity: "medium", reportedAgoEn: "21 days ago", reportedAgoHi: "21 दिन पहले", departmentEn: "Street Lighting · Municipal Council", departmentHi: "सड़क प्रकाश · नगर परिषद", roleEn: "Electrical Supervisor", roleHi: "विद्युत पर्यवेक्षक", escalationEn: "Ward Engineer · 1800-14-0014", escalationHi: "वार्ड अभियंता · 1800-14-0014", expectedEn: "Completed 24 Aug", expectedHi: "24 अगस्त को पूरा", timeline: [...roadTimeline, { status: "awaiting_confirmation", labelEn: "Awaiting your check", labelHi: "आपकी जाँच बाकी", date: "23 Aug · 18:10" }, { status: "confirmed", labelEn: "Confirmed by residents", labelHi: "निवासियों ने पुष्टि की", date: "24 Aug · 20:04" }],
  },
  {
    id: "PK-14037", category: "Water", titleEn: "Leaking pipe outside ration shop", titleHi: "राशन दुकान के बाहर पाइप लीक", descriptionEn: "Clean water has been running into the street since morning.", descriptionHi: "सुबह से साफ पानी सड़क पर बह रहा है।", address: "Nehru Market Road", lat: 28.6998, lng: 77.1005, image: "/images/water.svg", supporters: 7, aliases: ["A neighbour"], status: "reported", severity: "medium", reportedAgoEn: "4 hours ago", reportedAgoHi: "4 घंटे पहले", departmentEn: "Water Supply · Jal Board", departmentHi: "जल आपूर्ति · जल बोर्ड", roleEn: "Area Maintenance Supervisor", roleHi: "क्षेत्र रखरखाव पर्यवेक्षक", escalationEn: "Zone Control Room · 1800-14-0014", escalationHi: "क्षेत्र नियंत्रण कक्ष · 1800-14-0014", expectedEn: "Assessment within 24 hours", expectedHi: "24 घंटे में जाँच", timeline: roadTimeline.slice(0, 1),
  },
  {
    id: "PK-14025", category: "Waste", titleEn: "Overflowing bin near metro gate", titleHi: "मेट्रो गेट के पास भरा कूड़ादान", descriptionEn: "The public bin is overflowing onto the pavement.", descriptionHi: "सार्वजनिक कूड़ादान भरकर फुटपाथ पर फैल रहा है।", address: "Model Town Metro Gate 2", lat: 28.7081, lng: 77.1012, image: "/images/waste.svg", supporters: 18, aliases: ["Zoya", "A neighbour"], status: "awaiting_confirmation", severity: "medium", reportedAgoEn: "8 days ago", reportedAgoHi: "8 दिन पहले", departmentEn: "Sanitation · Municipal Council", departmentHi: "स्वच्छता · नगर परिषद", roleEn: "Sanitary Inspector, Ward 14", roleHi: "स्वच्छता निरीक्षक, वार्ड 14", escalationEn: "Zonal Sanitation Officer · 1800-14-0014", escalationHi: "क्षेत्रीय स्वच्छता अधिकारी · 1800-14-0014", expectedEn: "Marked complete today", expectedHi: "आज पूरा बताया गया", mine: true, timeline: [...roadTimeline, { status: "awaiting_confirmation", labelEn: "Awaiting your check", labelHi: "आपकी जाँच बाकी", date: "Today · 11:20", noteEn: "Department uploaded completion proof", noteHi: "विभाग ने पूर्णता का सबूत जोड़ा" }],
  },
];

export const seedIssues: Issue[] = rawSeedIssues.map((issue) => ({
  ...issue,
  image: assetPath(issue.image),
}));
